# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2


      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          git clone https://github.com/infiWang/openwrt.git -b cr660x
          cd openwrt/package
          git clone https://github.com/jerrykuku/luci-theme-argon.git
          cd ..
          wget https://gist.githubusercontent.com/hilaolu/2615e7afa477c8e164f6b179cb9dc5ec/raw/3120dd684b16d886c1942c3c90014bca217031ee/.config
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make -j2 V=s
